'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            'Register Syncfusion License
            Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("Mgo+DSMBaFt/QHRqVVhkVFpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF5jS39Td0xnXnxbcXRRQA==;Mgo+DSMBPh8sVXJ0S0J+XE9AflRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS31TdERjWHZad3dQR2JZUA==;ORg4AjUWIQA/Gnt2VVhkQlFacldJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkdiWX5XdHNWQ2FfWEI=;MTEwOTQ4NEAzMjMwMmUzNDJlMzBOLy9oemRmY01vTllJbjBmby9UTm8xY1U2dUdvcHpDcDI4MmdiVnU4Mk1BPQ==;MTEwOTQ4NUAzMjMwMmUzNDJlMzBoUHR2NXJIN3RYaW5uQmZOYmZUTUxVNWl5My9iQkhFekZPSU9oRjZUNUFBPQ==;NRAiBiAaIQQuGjN/V0Z+WE9EaFtKVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdUVhWH9feXBSRWVeUEN0;MTEwOTQ4N0AzMjMwMmUzNDJlMzBsaUdKVnhnR0FnQ1pIeFNYQkR0VU9JeUVQcklXazJQNzUrNUNqOG8rVzdrPQ==;MTEwOTQ4OEAzMjMwMmUzNDJlMzBoMEJGNmJlZ2ExalpFVFFnM29JU1JjY1orTXNFR2tkajMwUnFEWUljVlI0PQ==;Mgo+DSMBMAY9C3t2VVhkQlFacldJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkdiWX5XdHNWQ2JUVkM=;MTEwOTQ5MEAzMjMwMmUzNDJlMzBtUmRqY3Byd25BOUN4a0ZTMG91QkcxcERyRDB3dVlhQmFBUDBEZHQzMnBRPQ==;MTEwOTQ5MUAzMjMwMmUzNDJlMzBHdXJPMWd6R2dLLytqd3JVOVFwaFBieGtHdzA0OTVCZCsyNTVtbmwwTENzPQ==;MTEwOTQ5MkAzMjMwMmUzNDJlMzBsaUdKVnhnR0FnQ1pIeFNYQkR0VU9JeUVQcklXazJQNzUrNUNqOG8rVzdrPQ==")
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses

        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.GraphicalReport.frmMain
        End Sub
    End Class
End Namespace
